# Generated by Django 3.0.6 on 2020-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('real_name', models.TextField()),
                ('tz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='real_name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='url',
            new_name='tz',
        ),
        migrations.AddField(
            model_name='activity',
            name='user_activity',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
