# Generated by Django 3.0.6 on 2020-05-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0002_auto_20200506_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(default='W012A3CDE', on_delete=django.db.models.deletion.CASCADE, to='datamanagement.User'),
            preserve_default=False,
        ),
    ]
